### PR TITLE
Rename LICENCE to LICENSE

### PR DESCRIPTION
**Pull request by odsod**
¯\_(ツ)_/¯

### CODE REVIEW

**Comment by odsod** [comment]
Ah nevermind, my OCD calmed down. :)

**Comment by spkrka** [comment]
Should we really close this without merging?

If we are using UK english then licence is a verb and license is a noun, so we should use license,
If we are using US english then license is both a verb and a noun, and licence is not a thing.

Source: http://grammarist.com/spelling/licence-license/

**Comment by mbruggmann** [comment]
Agreed, LICENSE is better. I just copy-pasted this from `futures-extra`. :+1:

**Comment by mbruggmann** [comment]
Reading the source @spkrka mentioned, it'd appear like the noun is `license` in US english and `licence` international, but I'd still go with the US version since that is what Apache calls it upstream.

**Pull request merged**
