### PR TITLE
Port ConcurrecnyLimiter from FuturesExtra to work with CompletionStage

### PR DESCRIPTION
**Pull request by eshrubs**
This has been renamed to ConcurrencyReducer to avoid class conflicts
with FuturesExtra, as they use the same package as CompletableFutures

### CODE REVIEW

**Comment by eshrubs** [comment]
The coverage has been lowered, so the -1 from codcov. However this line is not covered in FuturesExtra. By my point of view we can never get null on that line, but perhaps if we do not releasing would be a bug? Not sure

**Comment by pettermahlen** [comment]
I think 'job' can be null if two threads race - both get `queue.isEmpty() == true`, but only one gets a non-null response from `queue.poll`? It's a hard case to test, I think.

**Comment by eshrubs** [comment]
@pettermahlen Yeah, I think this would be hard to test. `isEmpty()` for a `BlockingQueue` from my reading uses `size()` is implemented with a `ReentrantLock`. 

The logic here is correct however - we need to return the ticket if we didn't actually get a job. 

I wonder if this could be refactored to rely on `poll` instead of checking `isEmpty()` every time? Then we would requeue the job if we can't get a permit

```java
Job<T> job = null;
while (!(job = queue.poll()) == null) {
  if (!limit.tryAcquire()) {
    queue.enqueue(job);
    return null;
  }
  return job;
}
return null;
```

**Comment by pettermahlen** [comment]
I think that algorithm would reorder jobs? Perhaps flipping it around would be better:

```java
// speculatively try to acquire a permit
if (!limit.tryAcquire()) {
   return null;
}

Job<T> job = queue.poll();
if (job == null) {
   // nothing to do; return the permit
   limit.release();
}

return job;
```

**Comment by eshrubs** [comment]
Ah yes, ordering matters

**Comment by pettermahlen** [comment]
Well, I guess a good thing about my suggested algorithm (if it works), is it's not check-then-act on the queue, so there's no race between two threads. The case when 'queue is not empty' followed by 'poll returns null' doesn't exist. So the scenario that isn't tested doesn't exist with that version, I think.

**Comment by spkrka** [comment]
Not sure how to fix the untestable line - we can't reorder it as you mention, and we dont want to risk having jobs stuck on queue forever if they dont get pumped for some reason

**Comment by pettermahlen** [comment]
@spkrka what about my alternative algorithm? It looks safe to me, as well as a little more straightforward to understand?

**Comment by spkrka** [comment]
@pettermahlen I think you are right. I've done the refactoring as a PR here https://github.com/spotify/futures-extra/pull/28 which could be useful to review before we finish this review, as that one is shorter and easier to compare

**Comment by eshrubs** [comment]
@pettermahlen @spkrka Have rebased and moved the new grabJob over

**Pull request merged**
